//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.CategoryInBranches = new HashSet<CategoryInBranch>();
            this.ProofPurchases = new HashSet<ProofPurchase>();
        }
    
        public int brachId { get; set; }
        public string branchName { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string idManager { get; set; }
        public Nullable<int> idChainStore { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryInBranch> CategoryInBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProofPurchase> ProofPurchases { get; set; }
    }
}
