//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChainStore
    {
        public int chainStoreId { get; set; }
        public string chainStoreName { get; set; }
        public string idManager { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
